export const SITE_URL = 'https://koku-vitrini.yesilbasozancem.chatgpt.site';
export const WHATSAPP = '905382851139';

export const brands = [
  {slug:'french-avenue',name:'French Avenue',copy:'Modern niş parfüm yorumları, güçlü yayılım ve dikkat çekici şişe tasarımlarıyla öne çıkan seçkin koleksiyon.'},
  {slug:'afnan',name:'Afnan',copy:'Doğu ve Batı parfümerisini birleştiren, kalıcı ve karakterli erkek, kadın ve unisex kokular.'},
  {slug:'khadlaj',name:'Khadlaj',copy:'Geleneksel Arap parfümeri mirasını çağdaş koku profilleriyle buluşturan Dubai merkezli parfüm evi.'},
  {slug:'lattafa',name:'Lattafa',copy:'Geniş koku yelpazesi, güçlü performansı ve ulaşılabilir seçkileriyle sevilen Arap parfüm markası.'},
  {slug:'rayhaan',name:'Rayhaan',copy:'Ferahlık, şıklık ve günlük kullanımı bir araya getiren modern parfüm koleksiyonları.'},
  {slug:'rasasi',name:'Rasasi',copy:'Köklü parfümeri deneyimiyle ferah, baharatlı ve odunsu kompozisyonlar sunan seçkin marka.'},
  {slug:'armaf',name:'Armaf',copy:'Şehirli ve özgüvenli koku karakterleriyle erkek ve kadın parfümlerinde güçlü seçenekler.'},
  {slug:'fragrance-world',name:'Fragrance World',copy:'Farklı koku ailelerini keşfetmek isteyenlere zengin ve modern bir parfüm seçkisi.'}
];

export const categories = [
  {slug:'erkek-parfumleri',name:'Erkek Parfümleri',short:'Güçlü, rafine ve karakterli',gender:'Erkek',meta:'Kalıcı erkek parfümleri; odunsu, baharatlı, fresh ve aromatik seçeneklerle Koku Vitrini’nde. Tarzınıza uygun erkek kokusunu keşfedin.'},
  {slug:'kadin-parfumleri',name:'Kadın Parfümleri',short:'Zarif, cesur ve unutulmaz',gender:'Kadın',meta:'Kadın parfümleri; çiçeksi, meyvemsi, vanilyalı ve gurme koku seçenekleriyle Koku Vitrini’nde. İmza kokunuzu keşfedin.'},
  {slug:'unisex-parfumler',name:'Unisex Parfümler',short:'Sınırların ötesinde kokular',gender:'Unisex',meta:'Kadın ve erkek kullanımına uygun kalıcı unisex parfümler. Niş, odunsu, meyvemsi ve gurme seçenekleri Koku Vitrini’nde.'},
  {slug:'parfum-setleri',name:'Parfüm Setleri',short:'Hediye etmeye hazır seçkiler',gender:'Set',meta:'Parfüm hediye setleri ve keşif koleksiyonları. Özel günlere uygun kadın, erkek ve unisex parfüm setlerini inceleyin.'}
];

export const products = [
 {slug:'vulcan-feu-french-avenue-100-ml-unisex-parfum',name:'Vulcan Feu',brand:'French Avenue',gender:'Unisex',family:'Meyvemsi',size:'100 ML',price:3200,oldPrice:3800,color:'#d96d39',badge:'Çok Satan',rating:4.9,stock:12,notes:['Meyvemsi akorlar','Baharatlı dokunuşlar','Sıcak odunsu notalar'],short:'Canlı meyvelerle sıcak odunsu dokuları buluşturan, dikkat çekici unisex parfüm.',description:'Vulcan Feu, enerjik meyvemsi açılışını sıcak baharatlar ve modern odunsu dokularla dengeleyen karakterli bir unisex parfümdür. Gün boyu fark edilir bir iz bırakmak isteyenler için güçlü bir seçenek sunar.'},
 {slug:'liquid-brun-french-avenue-100-ml-erkek-parfum',name:'Liquid Brun',brand:'French Avenue',gender:'Erkek',family:'Gurme',size:'100 ML',price:2750,oldPrice:3500,color:'#7a432a',badge:'Editörün Seçimi',rating:5,stock:7,notes:['Tarçın','Vanilya','Amber ve odunsu notalar'],short:'Sıcak baharat, vanilya ve amber karakteriyle yoğun ve etkileyici erkek parfümü.',description:'Liquid Brun, sıcak baharatlı açılışı ve kremsi vanilya karakteriyle özellikle serin havalarda öne çıkan bir erkek parfümüdür. Amberli ve odunsu dip yapısı kompozisyona derinlik ve kalıcılık kazandırır.'},
 {slug:'aether-french-avenue-100-ml-unisex-parfum',name:'Aether',brand:'French Avenue',gender:'Unisex',family:'Aromatik',size:'100 ML',price:3450,oldPrice:5500,color:'#79927a',badge:'Yeni',rating:4.8,stock:6,notes:['Yeşil elma','Aromatik notalar','Misk ve odunsu notalar'],short:'Temiz, yeşil ve modern karakteriyle dört mevsime uyum sağlayan unisex koku.',description:'Aether, canlı yeşil dokuları aromatik ve temiz bir koku karakteriyle bir araya getirir. Ferah ama sıradan olmayan yapısı sayesinde gündüz kullanımından özel buluşmalara kadar geniş bir kullanım alanı sunar.'},
 {slug:'royal-blend-nero-french-avenue-100-ml-unisex-parfum',name:'Royal Blend Nero',brand:'French Avenue',gender:'Unisex',family:'Gurme',size:'100 ML',price:3350,oldPrice:3900,color:'#aa8b58',badge:'Sınırlı Stok',rating:4.9,stock:6,notes:['Tatlı meyveler','Baharatlı akorlar','Vanilya ve amber'],short:'Zengin, tatlı ve sıcak yapısıyla iz bırakan sofistike unisex parfüm.',description:'Royal Blend Nero, tatlı meyve akorlarını baharatlı ve amberli bir taban üzerinde sunar. Yoğun ve davetkâr karakteriyle akşam kullanımına ve serin mevsimlere çok yakışır.'},
 {slug:'tropical-kiss-french-avenue-80-ml-kadin-parfum',name:'Tropical Kiss',brand:'French Avenue',gender:'Kadın',family:'Meyvemsi',size:'80 ML',price:2950,oldPrice:3400,color:'#d59678',badge:'Popüler',rating:4.8,stock:1,notes:['Tropikal meyveler','Çiçeksi kalp','Vanilya ve misk'],short:'Tropikal meyveler ve yumuşak vanilyayla neşeli, çekici kadın parfümü.',description:'Tropical Kiss, parlak tropikal meyve notalarını feminen çiçeklerle ve yumuşak bir vanilya tabanıyla tamamlar. Enerjik, tatlı ve kolay fark edilen bir imza arayanlara hitap eder.'},
 {slug:'spectre-ghost-french-avenue-80-ml-erkek-parfum',name:'Spectre Ghost',brand:'French Avenue',gender:'Erkek',family:'Odunsu',size:'80 ML',price:3100,oldPrice:3650,color:'#c8c3b8',badge:'Çok Satan',rating:4.9,stock:5,notes:['Narenciye','Baharatlı kalp','Vanilya ve odunsu notalar'],short:'Modern vanilya, baharat ve odunsu notalarla güçlü erkek parfümü.',description:'Spectre Ghost, parlak açılışının ardından baharatlı ve kremsi bir karaktere dönüşür. Odunsu dip notaları kokuyu dengelerken belirgin ve modern bir iz bırakır.'},
 {slug:'pinnace-oryn-french-avenue-100-ml-unisex-parfum',name:'Pinnace Oryn',brand:'French Avenue',gender:'Unisex',family:'Fresh',size:'100 ML',price:2990,oldPrice:3500,color:'#e6b24f',badge:'Yeni',rating:4.7,stock:4,notes:['Narenciye','Aromatik notalar','Temiz misk'],short:'Canlı narenciye ve aromatik dokularla ferah, temiz unisex parfüm.',description:'Pinnace Oryn, enerjik narenciye açılışını aromatik bir kalp ve temiz misk tabanıyla buluşturur. İlkbahar ve yaz aylarında günlük kullanım için canlı bir alternatif sunar.'},
 {slug:'atlantis-extrait-french-avenue-100-ml-unisex-parfum',name:'Atlantis Extrait',brand:'French Avenue',gender:'Unisex',family:'Aquatik',size:'100 ML',price:3150,oldPrice:3700,color:'#5b899f',badge:'Popüler',rating:4.8,stock:4,notes:['Deniz notaları','Aromatik akorlar','Amber ve misk'],short:'Deniz esintili ferahlığı amber ve miskle derinleştiren unisex parfüm.',description:'Atlantis Extrait, deniz esintili ferah akorları aromatik nüanslarla birleştirir. Amber ve misk tabanı, taze karakteri daha kalıcı ve sofistike hale getirir.'},
 {slug:'9-pm-rebel-afnan-100-ml-unisex-parfum',name:'9 PM Rebel',brand:'Afnan',gender:'Unisex',family:'Meyvemsi',size:'100 ML',price:2650,oldPrice:4000,color:'#252525',badge:'Popüler',rating:4.9,stock:8,notes:['Meyvemsi notalar','Aromatik kalp','Amber ve odunsu notalar'],short:'Meyvemsi, dinamik ve modern karakteriyle gece kullanımına uygun unisex koku.',description:'9 PM Rebel, enerjik meyvemsi açılışını aromatik ve sıcak bir tabanla tamamlar. Sosyal ortamlar ve akşam kullanımı için modern, fark edilir ve genç bir karakter sunar.'},
 {slug:'9-pm-afnan-100-ml-erkek-parfum',name:'9 PM',brand:'Afnan',gender:'Erkek',family:'Aromatik',size:'100 ML',price:3050,oldPrice:3400,color:'#171717',badge:'Çok Satan',rating:4.9,stock:9,notes:['Elma ve bergamot','Tarçın ve lavanta','Vanilya ve amber'],short:'Tatlı, aromatik ve sıcak yapısıyla sevilen gece parfümü.',description:'Afnan 9 PM; meyvemsi açılış, aromatik baharatlar ve sıcak vanilya tabanıyla güçlü bir erkek kokusudur. Özellikle akşam ve serin hava kullanımında dikkat çekici performans sunar.'},
 {slug:'karus-blu-spice-khadlaj-100-ml-erkek-parfum',name:'Karus Blu Spice',brand:'Khadlaj',gender:'Erkek',family:'Baharatlı',size:'100 ML',price:2990,oldPrice:3600,color:'#497d9d',badge:'Yeni',rating:4.7,stock:5,notes:['Taze baharatlar','Aromatik notalar','Odunsu taban'],short:'Taze baharatlarla mavi koku ferahlığını birleştiren modern erkek parfümü.',description:'Karus Blu Spice, taze ve aromatik yapıyı canlı baharatlar ve odunsu bir tabanla dengeler. Günlük kullanıma uygun, temiz ve özgüvenli bir erkek parfümü karakterine sahiptir.'},
 {slug:'shiyaaka-snow-khadlaj-100-ml-unisex-parfum',name:'Shiyaaka Snow',brand:'Khadlaj',gender:'Unisex',family:'Fresh',size:'100 ML',price:2850,oldPrice:3300,color:'#dadbd6',badge:'Yeni',rating:4.7,stock:4,notes:['Narenciye','Temiz çiçekler','Misk'],short:'Temiz, serin ve ferah karakteriyle günlük kullanıma uygun unisex parfüm.',description:'Shiyaaka Snow, parlak narenciye notalarını temiz çiçekler ve miskle tamamlayan ferah bir kompozisyondur. Sade, bakımlı ve modern bir koku izlenimi verir.'},
 {slug:'hawas-ice-rasasi-100-ml-erkek-parfum',name:'Hawas Ice',brand:'Rasasi',gender:'Erkek',family:'Aquatik',size:'100 ML',price:3450,oldPrice:3900,color:'#82b8d0',badge:'Çok Satan',rating:4.9,stock:7,notes:['Narenciye ve meyveler','Aquatik notalar','Misk ve odunsu notalar'],short:'Buz gibi ferahlığı meyvemsi ve aquatik dokularla sunan erkek parfümü.',description:'Hawas Ice, parlak meyve ve narenciye notalarını aquatik bir kalple bir araya getirir. Temiz misk ve odunsu taban, yaz aylarında dikkat çeken ferah bir iz oluşturur.'},
 {slug:'azul-rayhaan-100-ml-erkek-parfum',name:'Azul',brand:'Rayhaan',gender:'Erkek',family:'Narenciye',size:'100 ML',price:2350,oldPrice:2800,color:'#88b9c9',badge:'Yaz Seçkisi',rating:4.6,stock:6,notes:['Narenciye','Beyaz çiçekler','Temiz misk'],short:'Parlak narenciye ve temiz miskle hafif, ferah erkek parfümü.',description:'Rayhaan Azul, canlı narenciye açılışı ve temiz misk tabanıyla sıcak havalara uygun ferah bir profil sunar. Günlük kullanımda sade, bakımlı ve enerjik bir etki bırakır.'},
 {slug:'his-confession-lattafa-100-ml-erkek-parfum',name:'His Confession',brand:'Lattafa',gender:'Erkek',family:'Odunsu',size:'100 ML',price:2700,oldPrice:3150,color:'#876c59',badge:'Popüler',rating:4.8,stock:3,notes:['Baharatlı notalar','İris dokusu','Amber ve odunsu notalar'],short:'Baharatlı, pudramsı ve odunsu çizgide sofistike erkek parfümü.',description:'His Confession, baharatlı açılışını yumuşak pudramsı dokular ve sıcak odunsu notalarla tamamlar. Şık, dengeli ve akşam kullanımına uygun bir karakter taşır.'},
 {slug:'khamrah-waha-lattafa-100-ml-unisex-parfum',name:'Khamrah Waha',brand:'Lattafa',gender:'Unisex',family:'Gurme',size:'100 ML',price:2900,oldPrice:3400,color:'#8e5133',badge:'Yeni',rating:4.8,stock:5,notes:['Tatlı meyveler','Sıcak baharatlar','Vanilya ve amber'],short:'Yoğun tatlılık ve sıcak baharatlarla zengin, davetkâr unisex parfüm.',description:'Khamrah Waha, tatlı meyve akorlarını sıcak baharatlar, vanilya ve amberle harmanlar. Serin havalarda ve özel akşamlarda belirgin bir koku izi isteyenlere uygundur.'},
 {slug:'club-de-nuit-milestone-armaf-105-ml-unisex-parfum',name:'Club de Nuit Milestone',brand:'Armaf',gender:'Unisex',family:'Aquatik',size:'105 ML',price:3250,oldPrice:3800,color:'#c1a45e',badge:'Klasik',rating:4.8,stock:4,notes:['Deniz tuzu','Meyvemsi notalar','Misk ve odunsu notalar'],short:'Tuzlu deniz esintisi ve meyvemsi ferahlıkla özgün unisex parfüm.',description:'Club de Nuit Milestone, tuzlu aquatik yapıyı canlı meyveler ve temiz bir misk tabanıyla birleştirir. İlkbahar ve yaz aylarında farklı ve kalıcı bir ferahlık sunar.'},
 {slug:'discovery-diamond-collection-ibraq-10x10-ml-parfum-seti',name:'Discovery Diamond Collection',brand:'Fragrance World',gender:'Set',family:'Keşif Seti',size:'10 × 10 ML',price:4950,oldPrice:7800,color:'#4c4b50',badge:'Hediye Seti',rating:4.9,stock:3,notes:['10 farklı koku','Taşınabilir şişeler','Hediye kutusu'],short:'On farklı kokuyu keşfetmek ve hediye etmek için hazırlanmış parfüm seti.',description:'Discovery Diamond Collection, farklı koku karakterlerini 10 ml boyutlarda bir araya getiren kapsamlı bir keşif setidir. Kendi favorisini bulmak isteyenler ve şık bir hediye arayanlar için ideal bir seçenektir.'}
];

// Koku Bulucu için editöryal ürün profilleri. Gerçek katalog aktarımında bu
// alanlar üretici nota piramidi ve ürün performans verileriyle güncellenir.
export const finderProfiles = {
 'vulcan-feu-french-avenue-100-ml-unisex-parfum':{notes:['Meyvemsi','Baharatlı','Odunsu'],seasons:['İlkbahar','Sonbahar','Kış'],occasions:['Günlük','Akşam','Özel gün'],intensity:'Güçlü'},
 'liquid-brun-french-avenue-100-ml-erkek-parfum':{notes:['Tarçın','Vanilya','Amber','Odunsu'],seasons:['Sonbahar','Kış'],occasions:['Akşam','Özel gün'],intensity:'Güçlü'},
 'aether-french-avenue-100-ml-unisex-parfum':{notes:['Yeşil elma','Aromatik','Misk','Odunsu'],seasons:['İlkbahar','Yaz','Sonbahar'],occasions:['Günlük','Ofis','Özel gün'],intensity:'Orta'},
 'royal-blend-nero-french-avenue-100-ml-unisex-parfum':{notes:['Meyvemsi','Baharatlı','Vanilya','Amber'],seasons:['Sonbahar','Kış'],occasions:['Akşam','Özel gün'],intensity:'Güçlü'},
 'tropical-kiss-french-avenue-80-ml-kadin-parfum':{notes:['Tropikal meyveler','Çiçeksi','Vanilya','Misk'],seasons:['İlkbahar','Yaz'],occasions:['Günlük','Akşam'],intensity:'Orta'},
 'spectre-ghost-french-avenue-80-ml-erkek-parfum':{notes:['Narenciye','Baharatlı','Vanilya','Odunsu'],seasons:['Sonbahar','Kış'],occasions:['Akşam','Özel gün'],intensity:'Güçlü'},
 'pinnace-oryn-french-avenue-100-ml-unisex-parfum':{notes:['Narenciye','Aromatik','Misk'],seasons:['İlkbahar','Yaz'],occasions:['Günlük','Ofis'],intensity:'Orta'},
 'atlantis-extrait-french-avenue-100-ml-unisex-parfum':{notes:['Deniz notaları','Aromatik','Amber','Misk'],seasons:['İlkbahar','Yaz'],occasions:['Günlük','Ofis'],intensity:'Orta'},
 '9-pm-rebel-afnan-100-ml-unisex-parfum':{notes:['Meyvemsi','Aromatik','Amber','Odunsu'],seasons:['Sonbahar','Kış'],occasions:['Akşam','Özel gün'],intensity:'Güçlü'},
 '9-pm-afnan-100-ml-erkek-parfum':{notes:['Elma','Bergamot','Tarçın','Lavanta','Vanilya','Amber'],seasons:['Sonbahar','Kış'],occasions:['Akşam','Özel gün'],intensity:'Güçlü'},
 'karus-blu-spice-khadlaj-100-ml-erkek-parfum':{notes:['Baharatlı','Aromatik','Odunsu'],seasons:['İlkbahar','Sonbahar'],occasions:['Günlük','Ofis'],intensity:'Orta'},
 'shiyaaka-snow-khadlaj-100-ml-unisex-parfum':{notes:['Narenciye','Çiçeksi','Misk'],seasons:['İlkbahar','Yaz'],occasions:['Günlük','Ofis'],intensity:'Hafif'},
 'hawas-ice-rasasi-100-ml-erkek-parfum':{notes:['Narenciye','Meyvemsi','Deniz notaları','Misk','Odunsu'],seasons:['İlkbahar','Yaz'],occasions:['Günlük','Spor','Akşam'],intensity:'Güçlü'},
 'azul-rayhaan-100-ml-erkek-parfum':{notes:['Narenciye','Çiçeksi','Misk'],seasons:['İlkbahar','Yaz'],occasions:['Günlük','Ofis','Spor'],intensity:'Hafif'},
 'his-confession-lattafa-100-ml-erkek-parfum':{notes:['Baharatlı','İris','Amber','Odunsu'],seasons:['Sonbahar','Kış'],occasions:['Akşam','Özel gün'],intensity:'Güçlü'},
 'khamrah-waha-lattafa-100-ml-unisex-parfum':{notes:['Meyvemsi','Baharatlı','Vanilya','Amber'],seasons:['Sonbahar','Kış'],occasions:['Akşam','Özel gün'],intensity:'Güçlü'},
 'club-de-nuit-milestone-armaf-105-ml-unisex-parfum':{notes:['Deniz notaları','Meyvemsi','Misk','Odunsu'],seasons:['İlkbahar','Yaz'],occasions:['Günlük','Ofis','Özel gün'],intensity:'Orta'},
 'discovery-diamond-collection-ibraq-10x10-ml-parfum-seti':{notes:['Meyvemsi','Çiçeksi','Baharatlı','Odunsu'],seasons:['İlkbahar','Yaz','Sonbahar','Kış'],occasions:['Günlük','Ofis','Akşam','Özel gün'],intensity:'Orta'}
};

export const slugify = value => value.toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
export const brandBySlug = slug => brands.find(b=>b.slug===slug);
export const productsByBrand = slug => { const b=brandBySlug(slug); return b ? products.filter(p=>p.brand===b.name) : []; };
export const productBySlug = slug => products.find(p=>p.slug===slug);
export const categoryBySlug = slug => categories.find(c=>c.slug===slug);
export const productsByCategory = slug => { const c=categoryBySlug(slug); return c ? products.filter(p=>p.gender===c.gender) : []; };
export const money = value => new Intl.NumberFormat('tr-TR').format(value)+' ₺';
