import {notFound} from 'next/navigation';
import {Check,Clock,GitCompareArrows,PackageCheck,ShieldCheck,Star,Truck} from 'lucide-react';
import Breadcrumbs from '../../../components/Breadcrumbs';
import ProductVisual from '../../../components/ProductVisual';
import AddToCart from '../../../components/AddToCart';
import FavoriteButton from '../../../components/FavoriteButton';
import ProductCard from '../../../components/ProductCard';
import {getFinderProfile,money,productBySlug,products,SITE_URL,slugify,WHATSAPP} from '../../../lib/catalog';

export const dynamicParams=false;
export function generateStaticParams(){return products.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}){const {slug}=await params,p=productBySlug(slug);if(!p)return{};return{title:`${p.name} ${p.brand} ${p.size} ${p.gender} Parfüm`,description:`${p.name} ${p.brand} ${p.size}: ${p.short} Notaları, kullanım önerileri ve güncel fiyatını inceleyin.`,alternates:{canonical:`/urun/${slug}`},openGraph:{title:`${p.name} ${p.brand} ${p.size}`,description:p.short,type:'website',url:`/urun/${slug}`,...(p.image?{images:[p.image]}:{})}}}

export default async function Page({params}){
 const {slug}=await params,p=productBySlug(slug);if(!p)notFound();
 const profile=getFinderProfile(p);
 const related=products.filter(x=>x.slug!==p.slug&&(x.brand===p.brand||x.family===p.family)).slice(0,4);
 const schema={"@context":"https://schema.org","@type":"Product","@id":`${SITE_URL}/urun/${p.slug}#product`,"name":`${p.name} ${p.brand} ${p.size} ${p.gender} Parfüm`,"description":p.description,"sku":p.sku||p.slug.toUpperCase().slice(0,32),...(p.gtin?{"gtin":p.gtin}:{}),...(p.image?{"image":[p.image]}:{}),"brand":{"@type":"Brand","name":p.brand},"category":`${p.gender} Parfüm`,"size":p.size,"offers":{"@type":"Offer","url":`${SITE_URL}/urun/${p.slug}`,"priceCurrency":"TRY","price":p.price,"availability":p.stock>0?'https://schema.org/InStock':'https://schema.org/OutOfStock',"itemCondition":"https://schema.org/NewCondition","seller":{"@type":"Organization","name":"Koku Vitrini"},"shippingDetails":{"@type":"OfferShippingDetails","shippingDestination":{"@type":"DefinedRegion","addressCountry":"TR"},"deliveryTime":{"@type":"ShippingDeliveryTime","handlingTime":{"@type":"QuantitativeValue","minValue":0,"maxValue":1,"unitCode":"DAY"},"transitTime":{"@type":"QuantitativeValue","minValue":1,"maxValue":3,"unitCode":"DAY"}}}}};
 const categoryUrl=p.gender==='Erkek'?'/erkek-parfumleri':p.gender==='Kadın'?'/kadin-parfumleri':p.gender==='Set'?'/parfum-setleri':'/unisex-parfumler';
 return <main>
  <div className="product-page-wrap"><Breadcrumbs items={[{name:p.gender==='Set'?'Parfüm Setleri':`${p.gender} Parfümler`,url:categoryUrl},{name:p.name,url:`/urun/${p.slug}`}]} /><div className="product-detail"><div className="detail-visual"><span className="detail-badge">{p.badge}</span><ProductVisual product={p} large/></div><div className="detail-copy"><a className="detail-brand" href={`/marka/${slugify(p.brand)}`}>{p.brand}</a><h1>{p.name} <small>{p.size} {p.gender} Parfüm</small></h1>{p.rating>0&&<div className="detail-rating"><span>{[1,2,3,4,5].map(x=><Star key={x} fill="currentColor"/>)}</span><b>{p.rating}</b><small>Editör koku profili puanı</small></div>}<p className="lead">{p.short}</p><div className="detail-facts"><span><small>KOKU AİLESİ</small><b>{p.family}</b></span><span><small>KOKU YOĞUNLUĞU</small><b>{p.intensity||profile.intensity}</b></span><span><small>STOK</small><b>{p.stock>0?`${p.stock} adet`:'Tükendi'}</b></span></div><div className="detail-price"><b>{money(p.price)}</b>{p.oldPrice>p.price&&<><del>{money(p.oldPrice)}</del><span>%{Math.round((1-p.price/p.oldPrice)*100)} indirim</span></>}</div><AddToCart product={p} label="Sepete ekle"/><div className="detail-save-tools"><FavoriteButton product={p}/><a href={`/karsilastir?urun=${p.slug}`}><GitCompareArrows/> Karşılaştırmaya ekle</a></div><a className="direct-whatsapp" target="_blank" rel="noreferrer" href={`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(`Merhaba, ${p.name} ${p.size} hakkında bilgi almak istiyorum.`)}`}>WhatsApp’tan bilgi al</a><div className="detail-trust"><span><Truck/><b>1–3 iş gününde gönderim</b></span><span><ShieldCheck/><b>Güvenli sipariş desteği</b></span><span><PackageCheck/><b>Özenli paketleme</b></span></div></div></div></div>
  <section className="product-content"><div><p className="eyebrow">KOKU HİKÂYESİ</p><h2>{p.name} – {p.family} Koku Karakteri</h2><p>{p.description}</p><p>Parfümün tende gelişimi, uygulanan miktara, ten yapısına ve hava koşullarına göre değişebilir. En iyi deneyim için temiz tene ve nabız noktalarına uygulayın.</p></div><aside><h3>Öne Çıkan Notalar</h3>{p.notes.map((n,i)=><span key={n}><b>0{i+1}</b>{n}</span>)}</aside></section>
  <section className="usage-section"><div><Clock/><h3>Ne zaman kullanılır?</h3><p>{profile.seasons.length?`${profile.seasons.join(', ')} mevsimlerinde; ${profile.occasions.join(', ').toLocaleLowerCase('tr')} kullanımı için uygun bir karakter sunar.`:'Ürün profili tamamlandığında mevsim ve kullanım önerileri burada gösterilir.'}</p></div><div><Check/><h3>Kimler için uygun?</h3><p>{p.gender==='Unisex'?'Koku seçiminde cinsiyet sınırı aramayan, karakterli ve dengeli parfümleri sevenler için.':p.gender==='Set'?'Farklı kokuları denemek veya şık bir parfüm hediyesi vermek isteyenler için.':`${p.gender} parfümlerinde ${p.family.toLocaleLowerCase('tr')} ve dikkat çekici karakter arayanlar için.`}</p></div></section>
  {related.length>0&&<section className="home-section related"><div className="section-title"><div><p className="eyebrow">BUNLARI DA SEVEBİLİRSİN</p><h2>Benzer kokular</h2></div></div><div className="product-grid">{related.map(x=><ProductCard key={x.slug} product={x}/>)}</div></section>}
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
 </main>
}
